
///USERS
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "email" : "asdsadsdsdss@gdsasmail.com",
    "name" : "fassa",
    "password" : "pass",
    "identity_type" : "sadas", 
    "identity_number" : "67343sdsdsasdasasdasdasdd943",
    "address" : "asdsa"
}

###
GET http://localhost:3000/api/v1/users


###
GET http://localhost:3000/api/v1/users/50

###
PUT  http://localhost:3000/api/v1/users/99999
Content-Type: application/json

{
    "name" : "uodatedtesting",
    "email" : "uodatedtesting999.com",
    "password" : "newPassword"
}
###

DELETE  http://localhost:3000/api/v1/users/59

###
PUT  http://localhost:3000/api/v1/profile/26
Content-Type: application/json

{
     "identity_type" : "KTP",
     "identity_number" : "999999999999999999999999",
     "address" : "Bandung"
}







///ACCOUNTS

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "bankName" : "Bank fin2",
    "balance" : 10000000,
    "userId" : 26
}

###
GET http://localhost:3000/api/v1/accounts


###
GET http://localhost:3000/api/v1/accounts/25

###
PUT  http://localhost:3000/api/v1/accounts/25
Content-Type: application/json

{
    "bankName" : "newname"
}

###

DELETE  http://localhost:3000/api/v1/accounts/25







///TRANSACTIONS

###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "sourceId" : 19,
    "destinatonId" : 20,
    "amount" : 9999999
}


###
GET http://localhost:3000/api/v1/transactions

###
GET http://localhost:3000/api/v1/transactions/25



//WITHDRAW
###
PUT http://localhost:3000/api/v1/withdraw
Content-Type: application/json

{
    "bankId" : 18,
    "amount" : "99999"
}



//DEPOSIT
###
PUT http://localhost:3000/api/v1/deposit
Content-Type: application/json

{
    "bankId" : 18,
    "amount" : 9999
}
