
///USERS
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "email" : "finaltes2@gmail.com",
    "name" : "finalte2",
    "identity_type" : "driving license", 
    "identity_number" : "5423225134322",
    "address" : "Tangerang"
}

###
GET http://localhost:3000/api/v1/users


###
GET http://localhost:3000/api/v1/users/26

###
PUT  http://localhost:3000/api/v1/users/26
Content-Type: application/json

{
    "name" : "finalnew",
    "email" : "finalnew2@gmail.com"
}
###

DELETE  http://localhost:3000/api/v1/users/26

###
PUT  http://localhost:3000/api/v1/profile/26
Content-Type: application/json

{
     "identity_type" : "Passport",
     "identity_number" : "666666660",
     "address" : "Bandung"
}







///ACCOUNTS

###
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
    "bankName" : "Bank fin2",
    "balance" : 10000000,
    "userId" : 26
}

###
GET http://localhost:3000/api/v1/accounts


###
GET http://localhost:3000/api/v1/accounts/25

###
PUT  http://localhost:3000/api/v1/accounts/25
Content-Type: application/json

{
    "bankName" : "newname"
}

###

DELETE  http://localhost:3000/api/v1/accounts/25







///TRANSACTIONS

###
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
    "sourceId" : 19,
    "destinatonId" : 20,
    "amount" : 9999999
}


###
GET http://localhost:3000/api/v1/transactions

###
GET http://localhost:3000/api/v1/transactions/25



//WITHDRAW
###
PUT http://localhost:3000/api/v1/withdraw
Content-Type: application/json

{
    "bankId" : 18,
    "amount" : "99999"
}



//DEPOSIT
###
PUT http://localhost:3000/api/v1/deposit
Content-Type: application/json

{
    "bankId" : 18,
    "amount" : 9999
}
